### ISSUE TITLE
Got {0} instead of endpoint

### ISSUE THREAD

**Issue by EvilToasterDBU** [barncastle/Battle.Net-Installer#19]
Hello! I forked your app and tried to implement GUI.
Found an issue with Requester class: instead of BaseAddress  got "{0}". Is it possible to pass actual endpoint?
How is the BaseAddress obtained from {0}?
```BaseAddress = $"http://127.0.0.1:{port}/{{0}}";```

**Comment by barncastle** [comment]
The `{0}` is a string placeholder which is populated in the [SendAsync](https://github.com/barncastle/Battle.Net-Installer/blob/master/BNetInstaller/Requester.cs#L41) method. The idea was you create an AgentApp and call the endpoint methods from that rather than accessing the Requester class directly.

If you do want to talk to the Agent.exe directly all you need is the following, the rest of the Request class is just for serialization and convenience methods:

```c#
HttpClient _client = new();
_client.DefaultRequestHeaders.Add("User-Agent", "phoenix-agent/1.0");
```
