### ISSUE TITLE
Opening the app shows command prompt but immediately closes

### ISSUE THREAD

**Issue by StereopwnZ** [barncastle/Battle.Net-Installer#3]
I click on it and even if I run it as admin or not the command box shows up for about 1 second then immediately closes. I can't seem to figure out why this is happening.

**Comment by toannhanb7** [comment]
@StereopwnZ : you will need to run the app in command line instead of double-click on it. The command is something like
`bnetinstaller.exe --prod s2 --uid s2_enus --lang enus --dir "C:\Test"`

Please read the introduction first

**Comment by barncastle** [comment]
As @toannhanb7 said you need to run it from either command line or PowerShell. I've updated the README with some better instructions explaining how to do so. If you continue to have problems feel free to reopen this issue.

**Comment by StereopwnZ** [comment]
So when I do it that way it tells me BNetinstaller.exe is not a recognized  external command, operable program, or batch file.

**Comment by barncastle** [comment]
It sounds like cmd/ps thinks it is a global command rather than an application. You may need to either add quotes around your command and/or prefix it with `.\` which should tell it to look for a program e.g. `"bnetinstaller.exe" …` or `.\bnetinstaller.exe …`.

Anyway, I'm glad you got it working. I might look at adding some basic wizard at some point in the future if this becomes the defacto tool for installing new Blizzard titles. If anything else crops up, make a new issue and I'll take a look.
