### ISSUE TITLE
High CPU usage when downloading. 

### ISSUE THREAD

**Issue by Streiw** [barncastle/Battle.Net-Installer#5]
https://prnt.sc/11jl0ej

**Comment by barncastle** [comment]
This seems like a localised issue with your PC and/or Battle.net. This app is simply a wrapper around Battle.net and uses barely any resources; the most it does is query the game download status every 2 seconds. This CPU spike is more likely to be caused by Battle.net downloading and generating the game data archives or something else with your system. I'd try replicating the issue by using Battle.net to install another game.
